Genepop version 4.2, Number of migrants using private alleles
(see Barton & Slatkin, Heredity (1986),56:409-415)

File: D:\Pacific cod\DataAnalysis\PCod-Korea-repo\stacks_b8_verif\batch_8_filteredMAF_filteredIndivids30_filteredLoci_filteredHWE_filteredCR_genepop.txt (Korean Pacific cod filtered final genepop, stacks batch 8 MF 3/8/2018)

Number of populations detected : 9
Number of loci detected        : 5804

Mean sample size: 26.1549
Mean frequency of private alleles p(1)= 0.0603068

Number of migrants for mean N=10: 3.54285
Number of migrants for mean N=25: 1.55002
Number of migrants for mean N=50: 1.03691
Number of migrants after correction for size= 1.48158

Normal ending.
